export const ROLES = [
  { id: "Admin", name: "Admin" },
  { id: "Contributor", name: "Contributor" },
  { id: "SLT", name: "SLT" },
];

export const USERS = [
  { id: "cathy", fullName: "Cathy", role: "Admin", label: "Cathy (Mum, Admin)" },
  { id: "lenny", fullName: "Lenny", role: "Contributor", label: "Lenny (Dad, Contributor)" },
  { id: "kayleigh", fullName: "Kayleigh", role: "Contributor", label: "Kayleigh (LSA, Contributor)" },
  { id: "sinead", fullName: "Sinead", role: "SLT", label: "Sinead (SLT)" },
];

export const INITIAL_GESTALTS = [
  {
    id: "1",
    phrase: "Merry Christmas",
    source: "Peppa Pig (Christmas Episode)",
    meaning: "I am feeling overwhelmed or experiencing high arousal (joy/distress)",
    communicationFunction: "Sharing feeling / protesting",
    modelOptions: "Oh no, it fell down",
    stage: "1",
    dateOfEntry: "2026-01-28",
    inactiveDate: "2026-03-04",
    status: "Active",
    flaggedForSlt: true,
    createdBy: "Cathy",
    createdByRole: "Admin",
    createdAt: "2023-10-15T10:00:00Z",
    comments: [
      {
        id: "c1",
        author: "Cathy",
        text: "Said this twice today when his tower fell over.",
        role: "Admin",
        time: "10:30 AM",
      },
      {
        id: "c2",
        author: "Sinead",
        text: "Classic Stage 1. Let's try modeling \"Oh no, it fell!\" next time.",
        role: "SLT",
        time: "1:15 PM",
      },
    ],
  },
  {
    id: "2",
    phrase: "To infinity and beyond",
    source: "Toy Story",
    meaning: "I want to go outside / transition to a new activity",
    communicationFunction: "Requesting transition",
    modelOptions: "It's time for outside",
    stage: "2",
    dateOfEntry: "2026-01-28",
    inactiveDate: "",
    status: "Active",
    flaggedForSlt: false,
    createdBy: "Kayleigh",
    createdByRole: "Contributor",
    createdAt: "2023-11-01T09:00:00Z",
    comments: [
      {
        id: "c3",
        author: "Kayleigh",
        text: "Used this when lining up for recess today.",
        role: "Contributor",
        time: "Yesterday",
      },
    ],
  },
  {
    id: "3",
    phrase: "Ready steady go",
    source: "Nursery rhymes",
    meaning: "Anticipation / wanting me to push him on swing",
    communicationFunction: "Shared enjoyment",
    modelOptions: "Ready, steady, go!",
    stage: "1",
    dateOfEntry: "2026-03-04",
    inactiveDate: "",
    status: "Fading",
    flaggedForSlt: false,
    createdBy: "Lenny",
    createdByRole: "Contributor",
    createdAt: "2023-08-20T14:00:00Z",
    comments: [],
  },
];
